Bubble sort algorithm
chindrop/Bubble-Sort pull request #1
Opened 2020-05-26 15:06 UTC by 8Bts

In this project we implemented bubble sort algorithm, so we created two ruby methods called bubble_sort and bubble_sort_by. The First method requires an Integer array as a parameter. The second method also requires an Integer array but you also need to pass a block which will be used to sort an array.

2020-05-26 16:22 UTC, shshamim63 requested changes
## Status :traffic_light: Required Changes :tractor: 
___
Hi @8Bts and @chindrop :wave: 
Nice initiative, well-indented code. But there is a major issue that is blocking me to approve this right now. Let's take down the issue.
___
### :spades: Mandatory Changes :spades: 
___
- The bubble_sort method is not returning a properly sorted array. Check out the comment attached to the code block.
- The gif you have added is not working. Please fix it.
___
#### Please resolve the above-mentioned issues and send another review request.
___
## :herb: Happy Coding :herb: 
### Shakhawat Hossain

2020-05-26 16:22 UTC, shshamim63 commented on README.md
> +```
[Optional]
Replace line 12 with the following line. It will give you a fancy look.
```
```ruby
```
```

2020-05-26 16:22 UTC, shshamim63 commented on README.md
> +![Bubble Sort Animation](Bubble-sort-example.gif)
This animation is not rendering. It seems not included in the repo or the link is invalid.

2020-05-26 16:22 UTC, shshamim63 commented on main.rb
> +end
I tried to execute the method with an unsorted array. But did not receive the expected result.
```ruby
p bubble_sort([9,2,1,6,5,4,8,10,7,3]) # The result I got [2, 1, 6, 5, 4, 8, 9, 7, 3, 10]
```

2020-05-27 10:45 UTC, 8Bts commented
Thanks for review @shshamim63. We fixed problems mentioned by you.

2020-05-27 11:07 UTC, stratospherique approved these changes
### Great work implementing the suggested changes :clap: Congrats, the project is approved :heavy_check_mark: You may merge :+1: :+1: 

Keep up the good work :muscle: 
**_Ahmed Mahfoudh_**

2020-05-27 11:10 UTC, merged